import type { AppLocale } from '@/i18n/routing';

/** Spanish \\text{...} fragments in formulas-calculo-diferencial.md → locale. */
const EN: Record<string, string> = {
  ' está definido': ' is defined',
  ' es continua en ': ' is continuous at ',
  ' alcanza todo valor entre ': ' attains every value between ',
  'Discontinuidad removible en ': 'Removable discontinuity at ',
  ' no definido': ' not defined',
  'Discontinuidad de salto en ': 'Jump discontinuity at ',
  'Discontinuidad infinita en ': 'Infinite discontinuity at ',
  ' continuas en ': ' are continuous at ',
  ' continua en ': ' is continuous at ',
  ' tiene máximo y mínimo absolutos en ': ' attains absolute maximum and minimum on ',
  ' diferenciable en ': ' is differentiable at ',
  ' existe (finito)': ' exists (finite)',
  ' existe ': ' exists ',
  ' es punto crítico': ' is a critical point',
  ' tiene mínimo local en ': ' has a local minimum at ',
  ' tiene máximo local en ': ' has a local maximum at ',
  ' máximo local en ': ' local maximum at ',
  ' mínimo local en ': ' local minimum at ',
  ' cambia de signo en ': ' changes sign at ',
  ' punto de inflexión': ' inflection point',
  ' creciente en ': ' increasing on ',
  ' decreciente en ': ' decreasing on ',
  ' estrictamente creciente en ': ' strictly increasing on ',
  ' estrictamente decreciente en ': ' strictly decreasing on ',
  ' cóncava hacia arriba en ': ' concave up on ',
  ' cóncava hacia abajo en ': ' concave down on ',
  ' constante en ': ' constant on ',
  ' entre ': ' between ',
  ' y ': ' and ',
  ' cuando ': ' when ',
  ' o ': ' or ',
  ' o': ' or',
  ' en ': ' on ',
  ' a ': ' to ',
  'Dominio': 'Domain',
  'asíntotas': 'asymptotes',
  'asíntota horizontal': 'horizontal asymptote',
  'asíntota oblicua': 'oblique asymptote',
  'asíntota vertical de ': 'vertical asymptote at ',
  'combinar algebraicamente o usar conjugados/logaritmos': 'combine algebraically or use conjugates/logarithms',
  'esquema': 'sketch',
  'intersecciones': 'intercepts',
  'usar ': 'use ',
  'o no existe, y ': ' or does not exist, and ',
  ' no existe': ' does not exist',
};

const DE: Record<string, string> = {
  ' está definido': ' ist definiert',
  ' es continua en ': ' ist stetig in ',
  ' alcanza todo valor entre ': ' nimmt jeden Wert zwischen ',
  'Discontinuidad removible en ': 'Hebbare Unstetigkeit in ',
  ' no definido': ' nicht definiert',
  'Discontinuidad de salto en ': 'Sprungunstetigkeit in ',
  'Discontinuidad infinita en ': 'Unendliche Unstetigkeit in ',
  ' continuas en ': ' sind stetig in ',
  ' continua en ': ' ist stetig in ',
  ' tiene máximo y mínimo absolutos en ': ' hat absolutes Maximum und Minimum auf ',
  ' diferenciable en ': ' ist differenzierbar in ',
  ' existe (finito)': ' existiert (endlich)',
  ' existe ': ' existiert ',
  ' es punto crítico': ' ist ein kritischer Punkt',
  ' tiene mínimo local en ': ' hat ein lokales Minimum in ',
  ' tiene máximo local en ': ' hat ein lokales Maximum in ',
  ' máximo local en ': ' lokales Maximum in ',
  ' mínimo local en ': ' lokales Minimum in ',
  ' cambia de signo en ': ' wechselt das Vorzeichen in ',
  ' punto de inflexión': ' Wendepunkt',
  ' creciente en ': ' wachsend auf ',
  ' decreciente en ': ' fallend auf ',
  ' estrictamente creciente en ': ' streng wachsend auf ',
  ' estrictamente decreciente en ': ' streng fallend auf ',
  ' cóncava hacia arriba en ': ' konvex auf ',
  ' cóncava hacia abajo en ': ' konkav auf ',
  ' constante en ': ' konstant auf ',
  ' entre ': ' zwischen ',
  ' y ': ' und ',
  ' cuando ': ' wenn ',
  ' o ': ' oder ',
  ' o': ' oder',
  ' en ': ' auf ',
  ' a ': ' zu ',
  'Dominio': 'Definitionsbereich',
  'asíntotas': 'Asymptoten',
  'asíntota horizontal': 'horizontale Asymptote',
  'asíntota oblicua': 'schräge Asymptote',
  'asíntota vertical de ': 'vertikale Asymptote bei ',
  'combinar algebraicamente o usar conjugados/logaritmos':
    'algebraisch kombinieren oder Konjugierte/Logarithmen verwenden',
  'esquema': 'Skizze',
  'intersecciones': 'Schnittpunkte',
  'usar ': 'verwende ',
  'o no existe, y ': ' oder existiert nicht, und ',
  ' no existe': ' existiert nicht',
};

const FR: Record<string, string> = {
  ' está definido': ' est défini',
  ' es continua en ': ' est continue en ',
  ' alcanza todo valor entre ': ' atteint toute valeur entre ',
  'Discontinuidad removible en ': 'Discontinuité amovible en ',
  ' no definido': ' non défini',
  'Discontinuidad de salto en ': 'Discontinuité par saut en ',
  'Discontinuidad infinita en ': 'Discontinuité infinie en ',
  ' continuas en ': ' sont continues en ',
  ' continua en ': ' est continue en ',
  ' tiene máximo y mínimo absolutos en ': ' atteint max et min absolus sur ',
  ' diferenciable en ': ' est dérivable en ',
  ' existe (finito)': ' existe (fini)',
  ' existe ': ' existe ',
  ' es punto crítico': ' est un point critique',
  ' tiene mínimo local en ': ' a un minimum local en ',
  ' tiene máximo local en ': ' a un maximum local en ',
  ' máximo local en ': ' maximum local en ',
  ' mínimo local en ': ' minimum local en ',
  ' cambia de signo en ': ' change de signe en ',
  ' punto de inflexión': ' point d\'inflexion',
  ' creciente en ': ' croissante sur ',
  ' decreciente en ': ' décroissante sur ',
  ' estrictamente creciente en ': ' strictement croissante sur ',
  ' estrictamente decreciente en ': ' strictement décroissante sur ',
  ' cóncava hacia arriba en ': ' convexe sur ',
  ' cóncava hacia abajo en ': ' concave sur ',
  ' constante en ': ' constante sur ',
  ' entre ': ' entre ',
  ' y ': ' et ',
  ' cuando ': ' quand ',
  ' o ': ' ou ',
  ' o': ' ou',
  ' en ': ' sur ',
  ' a ': ' à ',
  'Dominio': 'Domaine',
  'asíntotas': 'asymptotes',
  'asíntota horizontal': 'asymptote horizontale',
  'asíntota oblicua': 'asymptote oblique',
  'asíntota vertical de ': 'asymptote verticale en ',
  'combinar algebraicamente o usar conjugados/logaritmos':
    'combiner algébriquement ou utiliser conjugués/logarithmes',
  'esquema': 'schéma',
  'intersecciones': 'intersections',
  'usar ': 'utiliser ',
  'o no existe, y ': ' ou n\'existe pas, et ',
  ' no existe': ' n\'existe pas',
};

const IT: Record<string, string> = {
  ' está definido': ' è definito',
  ' es continua en ': ' è continua in ',
  ' alcanza todo valor entre ': ' assume ogni valore tra ',
  'Discontinuidad removible en ': 'Discontinuità rimovibile in ',
  ' no definido': ' non definito',
  'Discontinuidad de salto en ': 'Discontinuità a salto in ',
  'Discontinuidad infinita en ': 'Discontinuità infinita in ',
  ' continuas en ': ' sono continue in ',
  ' continua en ': ' è continua in ',
  ' tiene máximo y mínimo absolutos en ': ' ha massimo e minimo assoluti su ',
  ' diferenciable en ': ' è derivabile in ',
  ' existe (finito)': ' esiste (finito)',
  ' existe ': ' esiste ',
  ' es punto crítico': ' è un punto critico',
  ' tiene mínimo local en ': ' ha un minimo locale in ',
  ' tiene máximo local en ': ' ha un massimo locale in ',
  ' máximo local en ': ' massimo locale in ',
  ' mínimo local en ': ' minimo locale in ',
  ' cambia de signo en ': ' cambia segno in ',
  ' punto de inflexión': ' punto di flesso',
  ' creciente en ': ' crescente su ',
  ' decreciente en ': ' decrescente su ',
  ' estrictamente creciente en ': ' strettamente crescente su ',
  ' estrictamente decreciente en ': ' strettamente decrescente su ',
  ' cóncava hacia arriba en ': ' concava verso l\'alto su ',
  ' cóncava hacia abajo en ': ' concava verso il basso su ',
  ' constante en ': ' costante su ',
  ' entre ': ' tra ',
  ' y ': ' e ',
  ' cuando ': ' quando ',
  ' o ': ' o ',
  ' o': ' o',
  ' en ': ' su ',
  ' a ': ' a ',
  'Dominio': 'Dominio',
  'asíntotas': 'asintoti',
  'asíntota horizontal': 'asintoto orizzontale',
  'asíntota oblicua': 'asintoto obliquo',
  'asíntota vertical de ': 'asintoto verticale in ',
  'combinar algebraicamente o usar conjugados/logaritmos':
    'combinare algebricamente o usare coniugati/logaritmi',
  'esquema': 'schema',
  'intersecciones': 'intersezioni',
  'usar ': 'usa ',
  'o no existe, y ': ' o non esiste, e ',
  ' no existe': ' non esiste',
};

const PT: Record<string, string> = {
  ' está definido': ' está definido',
  ' es continua en ': ' é contínua em ',
  ' alcanza todo valor entre ': ' atinge todo valor entre ',
  'Discontinuidad removible en ': 'Descontinuidade removível em ',
  ' no definido': ' não definido',
  'Discontinuidad de salto en ': 'Descontinuidade de salto em ',
  'Discontinuidad infinita en ': 'Descontinuidade infinita em ',
  ' continuas en ': ' são contínuas em ',
  ' continua en ': ' é contínua em ',
  ' tiene máximo y mínimo absolutos en ': ' tem máximo e mínimo absolutos em ',
  ' diferenciable en ': ' é diferenciável em ',
  ' existe (finito)': ' existe (finito)',
  ' existe ': ' existe ',
  ' es punto crítico': ' é ponto crítico',
  ' tiene mínimo local en ': ' tem mínimo local em ',
  ' tiene máximo local en ': ' tem máximo local em ',
  ' máximo local en ': ' máximo local em ',
  ' mínimo local en ': ' mínimo local em ',
  ' cambia de signo en ': ' muda de sinal em ',
  ' punto de inflexión': ' ponto de inflexão',
  ' creciente en ': ' crescente em ',
  ' decreciente en ': ' decrescente em ',
  ' estrictamente creciente en ': ' estritamente crescente em ',
  ' estrictamente decreciente en ': ' estritamente decrescente em ',
  ' cóncava hacia arriba en ': ' côncava para cima em ',
  ' cóncava hacia abajo en ': ' côncava para baixo em ',
  ' constante en ': ' constante em ',
  ' entre ': ' entre ',
  ' y ': ' e ',
  ' cuando ': ' quando ',
  ' o ': ' ou ',
  ' o': ' ou',
  ' en ': ' em ',
  ' a ': ' a ',
  'Dominio': 'Domínio',
  'asíntotas': 'assíntotas',
  'asíntota horizontal': 'assíntota horizontal',
  'asíntota oblicua': 'assíntota oblíqua',
  'asíntota vertical de ': 'assíntota vertical em ',
  'combinar algebraicamente o usar conjugados/logaritmos':
    'combinar algebricamente ou usar conjugados/logaritmos',
  'esquema': 'esquema',
  'intersecciones': 'interseções',
  'usar ': 'usar ',
  'o no existe, y ': ' ou não existe, e ',
  ' no existe': ' não existe',
};

const MAPS: Partial<Record<AppLocale, Record<string, string>>> = {
  en: EN,
  de: DE,
  fr: FR,
  it: IT,
  pt: PT,
};

export function localizeCalculoDiferencialLatexText(latex: string, locale: AppLocale): string {
  if (locale === 'es') return latex;
  const map = MAPS[locale] ?? EN;
  return latex.replace(/\\text\{([^}]*)\}/g, (match, inner: string) => {
    const translated = map[inner] ?? map[inner.trim()];
    return translated !== undefined ? `\\text{${translated}}` : match;
  });
}
