import type { AppLocale } from '@/i18n/routing';

/**
 * Display labels for content tag slugs. Slugs stay stable for API filtering;
 * only the visible label is localized.
 */
const TAG_LABELS: Record<Exclude<AppLocale, 'es'>, Record<string, string>> = {
  en: {
    algebra: 'algebra',
    'formula-algebra': 'algebra formula',
    'formula-fisica': 'physics formula',
    antiderivada: 'antiderivative',
    'apendice-antiderivadas': 'antiderivatives appendix',
    'apendice-equivalencias': 'equivalences appendix',
    aplicacion: 'application',
    'aplicaciones-integral': 'integral applications',
    aproximacion: 'approximation',
    area: 'area',
    'aritmetica-modular': 'modular arithmetic',
    booleana: 'boolean',
    cinematica: 'kinematics',
    'cinematica-1d': '1D kinematics',
    circular: 'circular',
    codigos: 'codes',
    'codigos-lineales': 'linear codes',
    colisiones: 'collisions',
    complejos: 'complex numbers',
    constantes: 'constants',
    'constantes-fisicas': 'physical constants',
    convergencia: 'convergence',
    'coordenadas-polares': 'polar coordinates',
    'criterio-convergencia': 'convergence test',
    cs: 'CS',
    'curvas-parametricas': 'parametric curves',
    descomposiciones: 'decompositions',
    'descomposiciones-matrices': 'matrix decompositions',
    determinantes: 'determinants',
    'determinantes-inversas': 'determinants and inverses',
    dominio: 'domain',
    ecuaciones: 'equations',
    'ecuaciones-diferenciales': 'differential equations',
    eigen: 'eigen',
    elasticidad: 'elasticity',
    electricidad: 'electricity',
    'electricidad-basica': 'basic electricity',
    energia: 'energy',
    equilibrio: 'equilibrium',
    'equilibrio-elasticidad': 'equilibrium and elasticity',
    equivalencia: 'equivalence',
    'espacios-vectoriales': 'vector spaces',
    estrategia: 'strategy',
    estructuras: 'structures',
    'estructuras-algebraicas': 'algebraic structures',
    'exponenciales-logaritmos': 'exponentials and logarithms',
    'expresiones-algebraicas': 'algebraic expressions',
    'expresiones-racionales': 'rational expressions',
    factorizacion: 'factorization',
    fisica: 'physics',
    fluidos: 'fluids',
    formula: 'formula',
    'fracciones-parciales': 'partial fractions',
    fronteras: 'boundaries',
    'fronteras-materias': 'subject boundaries',
    fuerzas: 'forces',
    funciones: 'functions',
    'funciones-racionales': 'rational functions',
    fundamentos: 'fundamentals',
    gravitacion: 'gravitation',
    guia: 'guide',
    'guia-enfoque': 'approach guide',
    'guia-metodos': 'methods guide',
    identidad: 'identity',
    identidades: 'identities',
    inecuaciones: 'inequalities',
    'integracion-numerica': 'numerical integration',
    'integracion-por-partes': 'integration by parts',
    'integral-definida': 'definite integral',
    'integral-definida-tfc': 'definite integral & FTC',
    'integral-impropia': 'improper integral',
    'integral-indefinida': 'indefinite integral',
    'integrales-impropias': 'improper integrals',
    'integrales-trigonometricas': 'trigonometric integrals',
    'leyes-de-newton': "Newton's laws",
    lineal: 'linear',
    logaritmos: 'logarithms',
    maclaurin: 'Maclaurin',
    'mapas-relaciones': 'relation maps',
    mas: 'SHM',
    matrices: 'matrices',
    'mecanica-de-fluidos': 'fluid mechanics',
    'minimos-cuadrados': 'least squares',
    modular: 'modular',
    momento: 'momentum',
    'momento-impulso-colisiones': 'momentum, impulse and collisions',
    'movimiento-2d-3d': '2D and 3D motion',
    'movimiento-circular': 'circular motion',
    newton: 'Newton',
    normas: 'norms',
    'normas-condicionamiento': 'norms and conditioning',
    notacion: 'notation',
    'notacion-dominios': 'notation and domains',
    'numeros-complejos': 'complex numbers',
    'numeros-propiedades': 'numbers and properties',
    ondas: 'waves',
    ortogonalidad: 'orthogonality',
    'ortogonalidad-proyecciones': 'orthogonality and projections',
    oscilaciones: 'oscillations',
    parametricas: 'parametric',
    polares: 'polar',
    polinomios: 'polynomials',
    'por-partes': 'by parts',
    potencias: 'powers',
    'potencias-radicales': 'powers and radicals',
    'productos-notables': 'notable products',
    propiedad: 'property',
    proyectiles: 'projectiles',
    radicales: 'radicals',
    reduccion: 'reduction',
    relaciones: 'relations',
    'restriccion-dominio': 'domain restriction',
    rotacion: 'rotation',
    series: 'series',
    'series-potencias-taylor': 'power series and Taylor',
    sistemas: 'systems',
    'sistemas-ecuaciones': 'systems of equations',
    sonido: 'sound',
    sucesiones: 'sequences',
    'sucesiones-series': 'sequences and series',
    'sucesiones-series-finitas': 'finite sequences and series',
    sustitucion: 'substitution',
    'sustitucion-trigonometrica': 'trigonometric substitution',
    tabla: 'table',
    taylor: 'Taylor',
    'tecnica-fundamental': 'fundamental technique',
    'teorema-fundamental': 'fundamental theorem',
    termodinamica: 'thermodynamics',
    trabajo: 'work',
    'trabajo-energia-potencia': 'work, energy and power',
    transformaciones: 'transformations',
    'transformaciones-lineales': 'linear transformations',
    trigonometrica: 'trigonometric',
    'valores-propios': 'eigenvalues',
    vectores: 'vectors',
    'vectores-algebra': 'vectors',
    volumen: 'volume',
  },
  de: {
    algebra: 'Algebra',
    'formula-algebra': 'Algebra-Formel',
    'formula-fisica': 'Physik-Formel',
    antiderivada: 'Stammfunktion',
    'apendice-antiderivadas': 'Anhang Stammfunktionen',
    'apendice-equivalencias': 'Anhang Äquivalenzen',
    aplicacion: 'Anwendung',
    'aplicaciones-integral': 'Integral-Anwendungen',
    aproximacion: 'Näherung',
    area: 'Fläche',
    'aritmetica-modular': 'modulare Arithmetik',
    booleana: 'boolesch',
    cinematica: 'Kinematik',
    'cinematica-1d': '1D-Kinematik',
    circular: 'kreisförmig',
    codigos: 'Codes',
    'codigos-lineales': 'lineare Codes',
    colisiones: 'Stöße',
    complejos: 'komplexe Zahlen',
    constantes: 'Konstanten',
    'constantes-fisicas': 'physikalische Konstanten',
    convergencia: 'Konvergenz',
    'coordenadas-polares': 'Polarkoordinaten',
    'criterio-convergencia': 'Konvergenzkriterium',
    cs: 'Informatik',
    'curvas-parametricas': 'parametrische Kurven',
    descomposiciones: 'Zerlegungen',
    'descomposiciones-matrices': 'Matrixzerlegungen',
    determinantes: 'Determinanten',
    'determinantes-inversas': 'Determinanten und Inverse',
    dominio: 'Definitionsbereich',
    ecuaciones: 'Gleichungen',
    'ecuaciones-diferenciales': 'Differentialgleichungen',
    eigen: 'Eigen',
    elasticidad: 'Elastizität',
    electricidad: 'Elektrizität',
    'electricidad-basica': 'Grundlagen Elektrizität',
    energia: 'Energie',
    equilibrio: 'Gleichgewicht',
    'equilibrio-elasticidad': 'Gleichgewicht und Elastizität',
    equivalencia: 'Äquivalenz',
    'espacios-vectoriales': 'Vektorräume',
    estrategia: 'Strategie',
    estructuras: 'Strukturen',
    'estructuras-algebraicas': 'algebraische Strukturen',
    'exponenciales-logaritmos': 'Exponentiale und Logarithmen',
    'expresiones-algebraicas': 'algebraische Ausdrücke',
    'expresiones-racionales': 'rationale Ausdrücke',
    factorizacion: 'Faktorisierung',
    fisica: 'Physik',
    fluidos: 'Fluide',
    formula: 'Formel',
    'fracciones-parciales': 'Partialbrüche',
    fronteras: 'Grenzen',
    'fronteras-materias': 'Fachgrenzen',
    fuerzas: 'Kräfte',
    funciones: 'Funktionen',
    'funciones-racionales': 'rationale Funktionen',
    fundamentos: 'Grundlagen',
    gravitacion: 'Gravitation',
    guia: 'Leitfaden',
    'guia-enfoque': 'Ansatzleitfaden',
    'guia-metodos': 'Methodenleitfaden',
    identidad: 'Identität',
    identidades: 'Identitäten',
    inecuaciones: 'Ungleichungen',
    'integracion-numerica': 'numerische Integration',
    'integracion-por-partes': 'partielle Integration',
    'integral-definida': 'bestimmtes Integral',
    'integral-definida-tfc': 'bestimmtes Integral & HDI',
    'integral-impropia': 'uneigentliches Integral',
    'integral-indefinida': 'unbestimmtes Integral',
    'integrales-impropias': 'uneigentliche Integrale',
    'integrales-trigonometricas': 'trigonometrische Integrale',
    'leyes-de-newton': 'Newtons Gesetze',
    lineal: 'linear',
    logaritmos: 'Logarithmen',
    maclaurin: 'Maclaurin',
    'mapas-relaciones': 'Beziehungskarten',
    mas: 'harmonische Schwingung',
    matrices: 'Matrizen',
    'mecanica-de-fluidos': 'Fluidmechanik',
    'minimos-cuadrados': 'kleinste Quadrate',
    modular: 'modular',
    momento: 'Impuls',
    'momento-impulso-colisiones': 'Impuls und Stöße',
    'movimiento-2d-3d': '2D- und 3D-Bewegung',
    'movimiento-circular': 'Kreisbewegung',
    newton: 'Newton',
    normas: 'Normen',
    'normas-condicionamiento': 'Normen und Kondition',
    notacion: 'Notation',
    'notacion-dominios': 'Notation und Definitionsbereiche',
    'numeros-complejos': 'komplexe Zahlen',
    'numeros-propiedades': 'Zahlen und Eigenschaften',
    ondas: 'Wellen',
    ortogonalidad: 'Orthogonalität',
    'ortogonalidad-proyecciones': 'Orthogonalität und Projektionen',
    oscilaciones: 'Schwingungen',
    parametricas: 'parametrisch',
    polares: 'polar',
    polinomios: 'Polynome',
    'por-partes': 'partiell',
    potencias: 'Potenzen',
    'potencias-radicales': 'Potenzen und Wurzeln',
    'productos-notables': 'binômische Formeln',
    propiedad: 'Eigenschaft',
    proyectiles: 'Wurfbewegung',
    radicales: 'Wurzeln',
    reduccion: 'Reduktion',
    relaciones: 'Beziehungen',
    'restriccion-dominio': 'Definitionsbereich',
    rotacion: 'Rotation',
    series: 'Reihen',
    'series-potencias-taylor': 'Potenzreihen und Taylor',
    sistemas: 'Systeme',
    'sistemas-ecuaciones': 'Gleichungssysteme',
    sonido: 'Schall',
    sucesiones: 'Folgen',
    'sucesiones-series': 'Folgen und Reihen',
    'sucesiones-series-finitas': 'endliche Folgen und Reihen',
    sustitucion: 'Substitution',
    'sustitucion-trigonometrica': 'trigonometrische Substitution',
    tabla: 'Tabelle',
    taylor: 'Taylor',
    'tecnica-fundamental': 'Grundtechnik',
    'teorema-fundamental': 'Hauptsatz',
    termodinamica: 'Thermodynamik',
    trabajo: 'Arbeit',
    'trabajo-energia-potencia': 'Arbeit, Energie und Leistung',
    transformaciones: 'Transformationen',
    'transformaciones-lineales': 'lineare Abbildungen',
    trigonometrica: 'trigonometrisch',
    'valores-propios': 'Eigenwerte',
    vectores: 'Vektoren',
    'vectores-algebra': 'Vektoren',
    volumen: 'Volumen',
  },
  fr: {
    algebra: 'algèbre',
    'formula-algebra': 'formule d’algèbre',
    'formula-fisica': 'formule de physique',
    antiderivada: 'primitive',
    'apendice-antiderivadas': 'annexe primitives',
    'apendice-equivalencias': 'annexe équivalences',
    aplicacion: 'application',
    'aplicaciones-integral': 'applications de l’intégrale',
    aproximacion: 'approximation',
    area: 'aire',
    'aritmetica-modular': 'arithmétique modulaire',
    booleana: 'booléen',
    cinematica: 'cinématique',
    'cinematica-1d': 'cinématique 1D',
    circular: 'circulaire',
    codigos: 'codes',
    'codigos-lineales': 'codes linéaires',
    colisiones: 'collisions',
    complejos: 'nombres complexes',
    constantes: 'constantes',
    'constantes-fisicas': 'constantes physiques',
    convergencia: 'convergence',
    'coordenadas-polares': 'coordonnées polaires',
    'criterio-convergencia': 'critère de convergence',
    cs: 'info',
    'curvas-parametricas': 'courbes paramétriques',
    descomposiciones: 'décompositions',
    'descomposiciones-matrices': 'décompositions matricielles',
    determinantes: 'déterminants',
    'determinantes-inversas': 'déterminants et inverses',
    dominio: 'domaine',
    ecuaciones: 'équations',
    'ecuaciones-diferenciales': 'équations différentielles',
    eigen: 'propre',
    elasticidad: 'élasticité',
    electricidad: 'électricité',
    'electricidad-basica': 'électricité de base',
    energia: 'énergie',
    equilibrio: 'équilibre',
    'equilibrio-elasticidad': 'équilibre et élasticité',
    equivalencia: 'équivalence',
    'espacios-vectoriales': 'espaces vectoriels',
    estrategia: 'stratégie',
    estructuras: 'structures',
    'estructuras-algebraicas': 'structures algébriques',
    'exponenciales-logaritmos': 'exponentielles et logarithmes',
    'expresiones-algebraicas': 'expressions algébriques',
    'expresiones-racionales': 'expressions rationnelles',
    factorizacion: 'factorisation',
    fisica: 'physique',
    fluidos: 'fluides',
    formula: 'formule',
    'fracciones-parciales': 'fractions partielles',
    fronteras: 'frontières',
    'fronteras-materias': 'frontières entre matières',
    fuerzas: 'forces',
    funciones: 'fonctions',
    'funciones-racionales': 'fonctions rationnelles',
    fundamentos: 'fondamentaux',
    gravitacion: 'gravitation',
    guia: 'guide',
    'guia-enfoque': 'guide d’approche',
    'guia-metodos': 'guide des méthodes',
    identidad: 'identité',
    identidades: 'identités',
    inecuaciones: 'inéquations',
    'integracion-numerica': 'intégration numérique',
    'integracion-por-partes': 'intégration par parties',
    'integral-definida': 'intégrale définie',
    'integral-definida-tfc': 'intégrale définie et TFC',
    'integral-impropia': 'intégrale impropre',
    'integral-indefinida': 'intégrale indéfinie',
    'integrales-impropias': 'intégrales impropres',
    'integrales-trigonometricas': 'intégrales trigonométriques',
    'leyes-de-newton': 'lois de Newton',
    lineal: 'linéaire',
    logaritmos: 'logarithmes',
    maclaurin: 'Maclaurin',
    'mapas-relaciones': 'cartes de relations',
    mas: 'oscillateur harmonique',
    matrices: 'matrices',
    'mecanica-de-fluidos': 'mécanique des fluides',
    'minimos-cuadrados': 'moindres carrés',
    modular: 'modulaire',
    momento: 'quantité de mouvement',
    'momento-impulso-colisiones': 'quantité de mouvement et collisions',
    'movimiento-2d-3d': 'mouvement 2D et 3D',
    'movimiento-circular': 'mouvement circulaire',
    newton: 'Newton',
    normas: 'normes',
    'normas-condicionamiento': 'normes et conditionnement',
    notacion: 'notation',
    'notacion-dominios': 'notation et domaines',
    'numeros-complejos': 'nombres complexes',
    'numeros-propiedades': 'nombres et propriétés',
    ondas: 'ondes',
    ortogonalidad: 'orthogonalité',
    'ortogonalidad-proyecciones': 'orthogonalité et projections',
    oscilaciones: 'oscillations',
    parametricas: 'paramétrique',
    polares: 'polaire',
    polinomios: 'polynômes',
    'por-partes': 'par parties',
    potencias: 'puissances',
    'potencias-radicales': 'puissances et radicaux',
    'productos-notables': 'identités remarquables',
    propiedad: 'propriété',
    proyectiles: 'projectiles',
    radicales: 'radicaux',
    reduccion: 'réduction',
    relaciones: 'relations',
    'restriccion-dominio': 'restriction de domaine',
    rotacion: 'rotation',
    series: 'séries',
    'series-potencias-taylor': 'séries entières et Taylor',
    sistemas: 'systèmes',
    'sistemas-ecuaciones': 'systèmes d’équations',
    sonido: 'son',
    sucesiones: 'suites',
    'sucesiones-series': 'suites et séries',
    'sucesiones-series-finitas': 'suites et séries finies',
    sustitucion: 'substitution',
    'sustitucion-trigonometrica': 'substitution trigonométrique',
    tabla: 'table',
    taylor: 'Taylor',
    'tecnica-fundamental': 'technique fondamentale',
    'teorema-fundamental': 'théorème fondamental',
    termodinamica: 'thermodynamique',
    trabajo: 'travail',
    'trabajo-energia-potencia': 'travail, énergie et puissance',
    transformaciones: 'transformations',
    'transformaciones-lineales': 'transformations linéaires',
    trigonometrica: 'trigonométrique',
    'valores-propios': 'valeurs propres',
    vectores: 'vecteurs',
    'vectores-algebra': 'vecteurs',
    volumen: 'volume',
  },
  it: {
    algebra: 'algebra',
    'formula-algebra': 'formula di algebra',
    'formula-fisica': 'formula di fisica',
    antiderivada: 'primitiva',
    'apendice-antiderivadas': 'appendice primitive',
    'apendice-equivalencias': 'appendice equivalenze',
    aplicacion: 'applicazione',
    'aplicaciones-integral': 'applicazioni dell’integrale',
    aproximacion: 'approssimazione',
    area: 'area',
    'aritmetica-modular': 'aritmetica modulare',
    booleana: 'booleana',
    cinematica: 'cinematica',
    'cinematica-1d': 'cinematica 1D',
    circular: 'circolare',
    codigos: 'codici',
    'codigos-lineales': 'codici lineari',
    colisiones: 'collisioni',
    complejos: 'numeri complessi',
    constantes: 'costanti',
    'constantes-fisicas': 'costanti fisiche',
    convergencia: 'convergenza',
    'coordenadas-polares': 'coordinate polari',
    'criterio-convergencia': 'criterio di convergenza',
    cs: 'informatica',
    'curvas-parametricas': 'curve parametriche',
    descomposiciones: 'scomposizioni',
    'descomposiciones-matrices': 'scomposizioni di matrici',
    determinantes: 'determinanti',
    'determinantes-inversas': 'determinanti e inverse',
    dominio: 'dominio',
    ecuaciones: 'equazioni',
    'ecuaciones-diferenciales': 'equazioni differenziali',
    eigen: 'autovalori',
    elasticidad: 'elasticità',
    electricidad: 'elettricità',
    'electricidad-basica': 'elettricità di base',
    energia: 'energia',
    equilibrio: 'equilibrio',
    'equilibrio-elasticidad': 'equilibrio ed elasticità',
    equivalencia: 'equivalenza',
    'espacios-vectoriales': 'spazi vettoriali',
    estrategia: 'strategia',
    estructuras: 'strutture',
    'estructuras-algebraicas': 'strutture algebriche',
    'exponenciales-logaritmos': 'esponenziali e logaritmi',
    'expresiones-algebraicas': 'espressioni algebriche',
    'expresiones-racionales': 'espressioni razionali',
    factorizacion: 'fattorizzazione',
    fisica: 'fisica',
    fluidos: 'fluidi',
    formula: 'formula',
    'fracciones-parciales': 'frazioni parziali',
    fronteras: 'confini',
    'fronteras-materias': 'confini tra materie',
    fuerzas: 'forze',
    funciones: 'funzioni',
    'funciones-racionales': 'funzioni razionali',
    fundamentos: 'fondamenti',
    gravitacion: 'gravitazione',
    guia: 'guida',
    'guia-enfoque': 'guida di approccio',
    'guia-metodos': 'guida ai metodi',
    identidad: 'identità',
    identidades: 'identità',
    inecuaciones: 'disequazioni',
    'integracion-numerica': 'integrazione numerica',
    'integracion-por-partes': 'integrazione per parti',
    'integral-definida': 'integrale definito',
    'integral-definida-tfc': 'integrale definito e TFC',
    'integral-impropia': 'integrale improprio',
    'integral-indefinida': 'integrale indefinito',
    'integrales-impropias': 'integrali impropri',
    'integrales-trigonometricas': 'integrali trigonometrici',
    'leyes-de-newton': 'leggi di Newton',
    lineal: 'lineare',
    logaritmos: 'logaritmi',
    maclaurin: 'Maclaurin',
    'mapas-relaciones': 'mappe di relazioni',
    mas: 'moto armonico',
    matrices: 'matrici',
    'mecanica-de-fluidos': 'meccanica dei fluidi',
    'minimos-cuadrados': 'minimi quadrati',
    modular: 'modulare',
    momento: 'quantità di moto',
    'momento-impulso-colisiones': 'quantità di moto e collisioni',
    'movimiento-2d-3d': 'moto 2D e 3D',
    'movimiento-circular': 'moto circolare',
    newton: 'Newton',
    normas: 'norme',
    'normas-condicionamiento': 'norme e condizionamento',
    notacion: 'notazione',
    'notacion-dominios': 'notazione e domini',
    'numeros-complejos': 'numeri complessi',
    'numeros-propiedades': 'numeri e proprietà',
    ondas: 'onde',
    ortogonalidad: 'ortogonalità',
    'ortogonalidad-proyecciones': 'ortogonalità e proiezioni',
    oscilaciones: 'oscillazioni',
    parametricas: 'parametriche',
    polares: 'polari',
    polinomios: 'polinomi',
    'por-partes': 'per parti',
    potencias: 'potenze',
    'potencias-radicales': 'potenze e radicali',
    'productos-notables': 'prodotti notevoli',
    propiedad: 'proprietà',
    proyectiles: 'proiettili',
    radicales: 'radicali',
    reduccion: 'riduzione',
    relaciones: 'relazioni',
    'restriccion-dominio': 'restrizione di dominio',
    rotacion: 'rotazione',
    series: 'serie',
    'series-potencias-taylor': 'serie di potenze e Taylor',
    sistemas: 'sistemi',
    'sistemas-ecuaciones': 'sistemi di equazioni',
    sonido: 'suono',
    sucesiones: 'successioni',
    'sucesiones-series': 'successioni e serie',
    'sucesiones-series-finitas': 'successioni e serie finite',
    sustitucion: 'sostituzione',
    'sustitucion-trigonometrica': 'sostituzione trigonometrica',
    tabla: 'tavola',
    taylor: 'Taylor',
    'tecnica-fundamental': 'tecnica fondamentale',
    'teorema-fundamental': 'teorema fondamentale',
    termodinamica: 'termodinamica',
    trabajo: 'lavoro',
    'trabajo-energia-potencia': 'lavoro, energia e potenza',
    transformaciones: 'trasformazioni',
    'transformaciones-lineales': 'trasformazioni lineari',
    trigonometrica: 'trigonometrica',
    'valores-propios': 'autovalori',
    vectores: 'vettori',
    'vectores-algebra': 'vettori',
    volumen: 'volume',
  },
  pt: {
    algebra: 'álgebra',
    'formula-algebra': 'fórmula de álgebra',
    'formula-fisica': 'fórmula de física',
    antiderivada: 'antiderivada',
    'apendice-antiderivadas': 'apêndice de antiderivadas',
    'apendice-equivalencias': 'apêndice de equivalências',
    aplicacion: 'aplicação',
    'aplicaciones-integral': 'aplicações da integral',
    aproximacion: 'aproximação',
    area: 'área',
    'aritmetica-modular': 'aritmética modular',
    booleana: 'booleana',
    cinematica: 'cinemática',
    'cinematica-1d': 'cinemática 1D',
    circular: 'circular',
    codigos: 'códigos',
    'codigos-lineales': 'códigos lineares',
    colisiones: 'colisões',
    complejos: 'números complexos',
    constantes: 'constantes',
    'constantes-fisicas': 'constantes físicas',
    convergencia: 'convergência',
    'coordenadas-polares': 'coordenadas polares',
    'criterio-convergencia': 'critério de convergência',
    cs: 'CC',
    'curvas-parametricas': 'curvas paramétricas',
    descomposiciones: 'decomposições',
    'descomposiciones-matrices': 'decomposições matriciais',
    determinantes: 'determinantes',
    'determinantes-inversas': 'determinantes e inversas',
    dominio: 'domínio',
    ecuaciones: 'equações',
    'ecuaciones-diferenciales': 'equações diferenciais',
    eigen: 'autovalores',
    elasticidad: 'elasticidade',
    electricidad: 'eletricidade',
    'electricidad-basica': 'eletricidade básica',
    energia: 'energia',
    equilibrio: 'equilíbrio',
    'equilibrio-elasticidad': 'equilíbrio e elasticidade',
    equivalencia: 'equivalência',
    'espacios-vectoriales': 'espaços vetoriais',
    estrategia: 'estratégia',
    estructuras: 'estruturas',
    'estructuras-algebraicas': 'estruturas algébricas',
    'exponenciales-logaritmos': 'exponenciais e logaritmos',
    'expresiones-algebraicas': 'expressões algébricas',
    'expresiones-racionales': 'expressões racionais',
    factorizacion: 'fatoração',
    fisica: 'física',
    fluidos: 'fluidos',
    formula: 'fórmula',
    'fracciones-parciales': 'frações parciais',
    fronteras: 'fronteiras',
    'fronteras-materias': 'fronteiras entre matérias',
    fuerzas: 'forças',
    funciones: 'funções',
    'funciones-racionales': 'funções racionais',
    fundamentos: 'fundamentos',
    gravitacion: 'gravitação',
    guia: 'guia',
    'guia-enfoque': 'guia de abordagem',
    'guia-metodos': 'guia de métodos',
    identidad: 'identidade',
    identidades: 'identidades',
    inecuaciones: 'inequações',
    'integracion-numerica': 'integração numérica',
    'integracion-por-partes': 'integração por partes',
    'integral-definida': 'integral definida',
    'integral-definida-tfc': 'integral definida e TFC',
    'integral-impropia': 'integral imprópria',
    'integral-indefinida': 'integral indefinida',
    'integrales-impropias': 'integrais impróprias',
    'integrales-trigonometricas': 'integrais trigonométricas',
    'leyes-de-newton': 'leis de Newton',
    lineal: 'linear',
    logaritmos: 'logaritmos',
    maclaurin: 'Maclaurin',
    'mapas-relaciones': 'mapas de relações',
    mas: 'MHS',
    matrices: 'matrizes',
    'mecanica-de-fluidos': 'mecânica dos fluidos',
    'minimos-cuadrados': 'mínimos quadrados',
    modular: 'modular',
    momento: 'momento',
    'momento-impulso-colisiones': 'momento, impulso e colisões',
    'movimiento-2d-3d': 'movimento 2D e 3D',
    'movimiento-circular': 'movimento circular',
    newton: 'Newton',
    normas: 'normas',
    'normas-condicionamiento': 'normas e condicionamento',
    notacion: 'notação',
    'notacion-dominios': 'notação e domínios',
    'numeros-complejos': 'números complexos',
    'numeros-propiedades': 'números e propriedades',
    ondas: 'ondas',
    ortogonalidad: 'ortogonalidade',
    'ortogonalidad-proyecciones': 'ortogonalidade e projeções',
    oscilaciones: 'oscilações',
    parametricas: 'paramétricas',
    polares: 'polares',
    polinomios: 'polinômios',
    'por-partes': 'por partes',
    potencias: 'potências',
    'potencias-radicales': 'potências e radicais',
    'productos-notables': 'produtos notáveis',
    propiedad: 'propriedade',
    proyectiles: 'projéteis',
    radicales: 'radicais',
    reduccion: 'redução',
    relaciones: 'relações',
    'restriccion-dominio': 'restrição de domínio',
    rotacion: 'rotação',
    series: 'séries',
    'series-potencias-taylor': 'séries de potências e Taylor',
    sistemas: 'sistemas',
    'sistemas-ecuaciones': 'sistemas de equações',
    sonido: 'som',
    sucesiones: 'sequências',
    'sucesiones-series': 'sequências e séries',
    'sucesiones-series-finitas': 'sequências e séries finitas',
    sustitucion: 'substituição',
    'sustitucion-trigonometrica': 'substituição trigonométrica',
    tabla: 'tabela',
    taylor: 'Taylor',
    'tecnica-fundamental': 'técnica fundamental',
    'teorema-fundamental': 'teorema fundamental',
    termodinamica: 'termodinâmica',
    trabajo: 'trabalho',
    'trabajo-energia-potencia': 'trabalho, energia e potência',
    transformaciones: 'transformações',
    'transformaciones-lineales': 'transformações lineares',
    trigonometrica: 'trigonométrica',
    'valores-propios': 'autovalores',
    vectores: 'vetores',
    'vectores-algebra': 'vetores',
    volumen: 'volume',
  },
};

/** Human-readable label for a tag slug in the active locale. */
export function localizeTagLabel(tag: string, locale: AppLocale): string {
  if (locale === 'es') return tag;
  return TAG_LABELS[locale][tag] ?? tag.replace(/-/g, ' ');
}
