'use client';

import { useLocale } from 'next-intl';
import type { AppLocale } from '@/i18n/routing';

type VizLabels = {
  swap: string;
  orderAb: string;
  groupLeft: string;
  groupRight: string;
  expandedForm: string;
  reorderFactor: string;
  closedEnds: string;
  inputA: string;
  inputB: string;
  showTerms: string;
  reflectH: string;
  showBasis: string;
  dependent: string;
  independent: string;
  gramStep: string;
  eigenvectors: string;
  applyInverse: string;
  svdStep: string;
  lowRank: string;
  luStep: string;
  roots2: string;
  root1: string;
  noRealRoot: string;
  orientedArea: string;
  noInverse: string;
  valid: string;
  error: string;
  dragVectors: string;
  tableAdd: string;
  tableMul: string;
  subspaceNote: string;
  homogeneousForm: string;
  fallbackViz: string;
  time: string;
  space: string;
  algebraTiles: string;
  termProduct: string;
  augmented: string;
  result: string;
  clickBitError: string;
  areaDet: string;
  fermatDemo: string;
  errorBit: string;
  pascalRow: string;
  addSquare: string;
  subtractSquare: string;
  degreeLabel: string;
  degreeHint: string;
  acute: string;
  rightAngle: string;
  obtuse: string;
  congruent: string;
  notCongruent: string;
  tableMatch: string;
  tableMismatch: string;
  equationOfRow: string;
  intersection: string;
  solutionRegion: string;
  noIntersection: string;
  svdRotate: string;
  svdScale: string;
  svdCompose: string;
  rankLabel: string;
  cellProduct: string;
  sameTotal: string;
  compareBothSides: string;
  degreeUnits: string;
  powerMerge: string;
  sameArea: string;
  oneSolution: string;
  infSolutions: string;
  noSolution: string;
  symmetricYes: string;
  symmetricNo: string;
  singularNoInv: string;
  rank1Demo: string;
  rankFull: string;
  encodeMsg: string;
  codeword: string;
  syndrome: string;
  validCodeword: string;
  invalidCodeword: string;
  qrStep: string;
  svdUnit: string;
  makePerp: string;
};

const LABELS: Record<AppLocale, VizLabels> = {
  es: {
    swap: 'Intercambiar',
    orderAb: 'Orden a,b',
    groupLeft: 'Agrupar izquierda',
    groupRight: 'Agrupar derecha',
    expandedForm: 'Forma expandida',
    reorderFactor: 'Reordenar / factorizar',
    closedEnds: 'Extremos cerrados',
    inputA: 'Entrada A',
    inputB: 'Entrada B',
    showTerms: 'Mostrar términos',
    reflectH: 'Reflexión horizontal',
    showBasis: 'Mostrar base',
    dependent: 'dependientes',
    independent: 'independientes',
    gramStep: 'Gram-Schmidt paso',
    eigenvectors: 'Eigenvectores',
    applyInverse: 'Aplicar A⁻¹',
    svdStep: 'Paso SVD/QR',
    lowRank: 'Rango bajo demo',
    luStep: 'Paso LU',
    roots2: '2 raíces',
    root1: '1 raíz',
    noRealRoot: 'sin raíz real',
    orientedArea: 'área orientada',
    noInverse: 'sin inverso',
    valid: 'válida',
    error: 'error',
    dragVectors: 'Arrastra las puntas de los vectores.',
    tableAdd: 'Tabla +',
    tableMul: 'Tabla ·',
    subspaceNote: 'Suma c1+c2 = [1, 1, 0] (cierre del subespacio)',
    homogeneousForm: 'forma homogénea grado',
    fallbackViz: 'Visualización',
    time: 'Tiempo',
    space: 'Espacio',
    algebraTiles: 'Piezas algebraicas',
    termProduct: 'Producto término × término',
    augmented: 'b (aumentada)',
    result: 'resultado',
    clickBitError: 'click bit para error',
    areaDet: 'área/det',
    fermatDemo: 'demo de Fermat',
    errorBit: 'error',
    pascalRow: 'Fila de Pascal',
    addSquare: 'Añadir (b/2)²',
    subtractSquare: 'Restar (b/2)²',
    degreeLabel: 'Grado total',
    degreeHint: 'Cada eje aporta su exponente al grado',
    acute: 'agudo',
    rightAngle: 'recto',
    obtuse: 'obtuso',
    congruent: 'a ≡ b (mod m)',
    notCongruent: 'a ≢ b (mod m)',
    tableMatch: 'coincide con la operación',
    tableMismatch: 'no coincide — revisa la fila',
    equationOfRow: 'Ecuación de la fila',
    intersection: 'intersección',
    solutionRegion: 'región solución',
    noIntersection: 'sin intersección (paralelas)',
    svdRotate: 'Vᵀ: rotar',
    svdScale: 'Σ: escalar',
    svdCompose: 'U: recomponer',
    rankLabel: 'rango',
    cellProduct: 'producto fila×columna',
    sameTotal: 'Mismo total',
    compareBothSides: 'Compara ambos lados: al mover a, b y c, las dos áreas cambian igual.',
    degreeUnits: 'unidades de grado',
    powerMerge: 'Abajo se juntan los bloques: los exponentes se suman.',
    sameArea: 'misma área',
    oneSolution: '1 solución',
    infSolutions: '∞ soluciones',
    noSolution: '∅ sin solución',
    symmetricYes: 'sí simétrica',
    symmetricNo: 'no simétrica',
    singularNoInv: 'A es singular (det = 0), no tiene inversa',
    rank1Demo: 'aprox. rango 1 (σ₂≈0)',
    rankFull: 'rango completo',
    encodeMsg: 'mensaje m',
    codeword: 'palabra c = mG',
    syndrome: 'síndrome s = Hcᵀ',
    validCodeword: 'palabra válida (s=0)',
    invalidCodeword: 'error detectado (s≠0)',
    qrStep: 'Paso QR',
    svdUnit: 'círculo unidad',
    makePerp: 'hacer ⊥',
  },
  en: {
    swap: 'Swap',
    orderAb: 'Order a,b',
    groupLeft: 'Group left',
    groupRight: 'Group right',
    expandedForm: 'Expanded form',
    reorderFactor: 'Reorder / factor',
    closedEnds: 'Closed endpoints',
    inputA: 'Input A',
    inputB: 'Input B',
    showTerms: 'Show terms',
    reflectH: 'Horizontal reflection',
    showBasis: 'Show basis',
    dependent: 'dependent',
    independent: 'independent',
    gramStep: 'Gram-Schmidt step',
    eigenvectors: 'Eigenvectors',
    applyInverse: 'Apply A⁻¹',
    svdStep: 'SVD/QR step',
    lowRank: 'Low-rank demo',
    luStep: 'LU step',
    roots2: '2 roots',
    root1: '1 root',
    noRealRoot: 'no real root',
    orientedArea: 'oriented area',
    noInverse: 'no inverse',
    valid: 'valid',
    error: 'error',
    dragVectors: 'Drag the vector tips.',
    tableAdd: 'Table +',
    tableMul: 'Table ·',
    subspaceNote: 'Sum c1+c2 = [1, 1, 0] (subspace closed)',
    homogeneousForm: 'homogeneous form degree',
    fallbackViz: 'Visualization',
    time: 'Time',
    space: 'Space',
    algebraTiles: 'Algebra tiles',
    termProduct: 'Term × term product',
    augmented: 'b (augmented)',
    result: 'result',
    clickBitError: 'click bit to flip error',
    areaDet: 'area/det',
    fermatDemo: 'Fermat demo',
    errorBit: 'error',
    pascalRow: 'Pascal row',
    addSquare: 'Add (b/2)²',
    subtractSquare: 'Subtract (b/2)²',
    degreeLabel: 'Total degree',
    degreeHint: 'Each axis contributes its exponent to the degree',
    acute: 'acute',
    rightAngle: 'right',
    obtuse: 'obtuse',
    congruent: 'a ≡ b (mod m)',
    notCongruent: 'a ≢ b (mod m)',
    tableMatch: 'matches the operation',
    tableMismatch: 'mismatch — check the row',
    equationOfRow: 'Equation of row',
    intersection: 'intersection',
    solutionRegion: 'solution region',
    noIntersection: 'no intersection (parallel)',
    svdRotate: 'Vᵀ: rotate',
    svdScale: 'Σ: scale',
    svdCompose: 'U: reassemble',
    rankLabel: 'rank',
    cellProduct: 'row×column product',
    sameTotal: 'Same total',
    compareBothSides: 'Compare both sides: when you move a, b and c, both areas change the same way.',
    degreeUnits: 'degree units',
    powerMerge: 'Below, the blocks join: the exponents add.',
    sameArea: 'same area',
    oneSolution: '1 solution',
    infSolutions: '∞ solutions',
    noSolution: '∅ no solution',
    symmetricYes: 'symmetric yes',
    symmetricNo: 'not symmetric',
    singularNoInv: 'A is singular (det = 0), no inverse',
    rank1Demo: 'rank-1 approx (σ₂≈0)',
    rankFull: 'full rank',
    encodeMsg: 'message m',
    codeword: 'codeword c = mG',
    syndrome: 'syndrome s = Hcᵀ',
    validCodeword: 'valid codeword (s=0)',
    invalidCodeword: 'error detected (s≠0)',
    qrStep: 'QR step',
    svdUnit: 'unit circle',
    makePerp: 'make ⊥',
  },
  de: {
    swap: 'Tauschen',
    orderAb: 'Reihenfolge a,b',
    groupLeft: 'Links gruppieren',
    groupRight: 'Rechts gruppieren',
    expandedForm: 'Ausmultipliziert',
    reorderFactor: 'Umordnen / faktorisieren',
    closedEnds: 'Geschlossene Enden',
    inputA: 'Eingang A',
    inputB: 'Eingang B',
    showTerms: 'Terme anzeigen',
    reflectH: 'Horizontale Spiegelung',
    showBasis: 'Basis anzeigen',
    dependent: 'abhängig',
    independent: 'unabhängig',
    gramStep: 'Gram-Schmidt Schritt',
    eigenvectors: 'Eigenvektoren',
    applyInverse: 'A⁻¹ anwenden',
    svdStep: 'SVD/QR Schritt',
    lowRank: 'Niedrigrang-Demo',
    luStep: 'LU Schritt',
    roots2: '2 Wurzeln',
    root1: '1 Wurzel',
    noRealRoot: 'keine reelle Wurzel',
    orientedArea: 'orientierte Fläche',
    noInverse: 'kein Inverses',
    valid: 'gültig',
    error: 'Fehler',
    dragVectors: 'Ziehe die Vektorspitzen.',
    tableAdd: 'Tabelle +',
    tableMul: 'Tabelle ·',
    subspaceNote: 'Summe c1+c2 = [1, 1, 0] (Unterraum abgeschlossen)',
    homogeneousForm: 'homogene Form Grad',
    fallbackViz: 'Visualisierung',
    time: 'Zeit',
    space: 'Speicher',
    algebraTiles: 'Algebra-Kacheln',
    termProduct: 'Term × Term Produkt',
    augmented: 'b (erweitert)',
    result: 'Ergebnis',
    clickBitError: 'Bit anklicken für Fehler',
    areaDet: 'Fläche/det',
    fermatDemo: 'Fermat-Demo',
    errorBit: 'Fehler',
    pascalRow: 'Pascal-Zeile',
    addSquare: '(b/2)² hinzufügen',
    subtractSquare: '(b/2)² abziehen',
    degreeLabel: 'Gesamtgrad',
    degreeHint: 'Jede Achse trägt ihren Exponenten zum Grad bei',
    acute: 'spitz',
    rightAngle: 'recht',
    obtuse: 'stumpf',
    congruent: 'a ≡ b (mod m)',
    notCongruent: 'a ≢ b (mod m)',
    tableMatch: 'stimmt mit der Operation überein',
    tableMismatch: 'stimmt nicht — Zeile prüfen',
    equationOfRow: 'Gleichung der Zeile',
    intersection: 'Schnittpunkt',
    solutionRegion: 'Lösungsbereich',
    noIntersection: 'kein Schnitt (parallel)',
    svdRotate: 'Vᵀ: drehen',
    svdScale: 'Σ: skalieren',
    svdCompose: 'U: zusammensetzen',
    rankLabel: 'Rang',
    cellProduct: 'Zeile×Spalte-Produkt',
    sameTotal: 'Gleiche Summe',
    compareBothSides: 'Vergleiche beide Seiten: Wenn du a, b und c bewegst, ändern sich beide Flächen gleich.',
    degreeUnits: 'Gradeinheiten',
    powerMerge: 'Unten verbinden sich die Blöcke: die Exponenten addieren sich.',
    sameArea: 'gleiche Fläche',
    oneSolution: '1 Lösung',
    infSolutions: '∞ Lösungen',
    noSolution: '∅ keine Lösung',
    symmetricYes: 'symmetrisch ja',
    symmetricNo: 'nicht symmetrisch',
    singularNoInv: 'A ist singulär (det = 0), keine Inverse',
    rank1Demo: 'Rang-1-Näherung (σ₂≈0)',
    rankFull: 'voller Rang',
    encodeMsg: 'Nachricht m',
    codeword: 'Codewort c = mG',
    syndrome: 'Syndrom s = Hcᵀ',
    validCodeword: 'gültiges Codewort (s=0)',
    invalidCodeword: 'Fehler erkannt (s≠0)',
    qrStep: 'QR-Schritt',
    svdUnit: 'Einheitskreis',
    makePerp: '⊥ machen',
  },
  fr: {
    swap: 'Échanger',
    orderAb: 'Ordre a,b',
    groupLeft: 'Grouper à gauche',
    groupRight: 'Grouper à droite',
    expandedForm: 'Forme développée',
    reorderFactor: 'Réordonner / factoriser',
    closedEnds: 'Extrémités fermées',
    inputA: 'Entrée A',
    inputB: 'Entrée B',
    showTerms: 'Afficher les termes',
    reflectH: 'Réflexion horizontale',
    showBasis: 'Afficher la base',
    dependent: 'dépendants',
    independent: 'indépendants',
    gramStep: 'Étape Gram-Schmidt',
    eigenvectors: 'Vecteurs propres',
    applyInverse: 'Appliquer A⁻¹',
    svdStep: 'Étape SVD/QR',
    lowRank: 'Démo rang faible',
    luStep: 'Étape LU',
    roots2: '2 racines',
    root1: '1 racine',
    noRealRoot: 'pas de racine réelle',
    orientedArea: 'aire orientée',
    noInverse: 'pas d’inverse',
    valid: 'valide',
    error: 'erreur',
    dragVectors: 'Faites glisser les pointes des vecteurs.',
    tableAdd: 'Table +',
    tableMul: 'Table ·',
    subspaceNote: 'Somme c1+c2 = [1, 1, 0] (sous-espace fermé)',
    homogeneousForm: 'forme homogène degré',
    fallbackViz: 'Visualisation',
    time: 'Temps',
    space: 'Espace',
    algebraTiles: 'Tuiles algébriques',
    termProduct: 'Produit terme × terme',
    augmented: 'b (augmentée)',
    result: 'résultat',
    clickBitError: 'cliquer un bit pour erreur',
    areaDet: 'aire/det',
    fermatDemo: 'démo de Fermat',
    errorBit: 'erreur',
    pascalRow: 'Ligne de Pascal',
    addSquare: 'Ajouter (b/2)²',
    subtractSquare: 'Soustraire (b/2)²',
    degreeLabel: 'Degré total',
    degreeHint: 'Chaque axe contribue son exposant au degré',
    acute: 'aigu',
    rightAngle: 'droit',
    obtuse: 'obtus',
    congruent: 'a ≡ b (mod m)',
    notCongruent: 'a ≢ b (mod m)',
    tableMatch: 'correspond à l’opération',
    tableMismatch: 'ne correspond pas — vérifier la ligne',
    equationOfRow: 'Équation de la ligne',
    intersection: 'intersection',
    solutionRegion: 'région solution',
    noIntersection: 'pas d’intersection (parallèles)',
    svdRotate: 'Vᵀ : rotation',
    svdScale: 'Σ : échelle',
    svdCompose: 'U : recomposer',
    rankLabel: 'rang',
    cellProduct: 'produit ligne×colonne',
    sameTotal: 'Même total',
    compareBothSides: 'Compare les deux côtés : quand tu bouges a, b et c, les deux aires changent pareil.',
    degreeUnits: 'unités de degré',
    powerMerge: 'En bas, les blocs se rejoignent : les exposants s’additionnent.',
    sameArea: 'même aire',
    oneSolution: '1 solution',
    infSolutions: '∞ solutions',
    noSolution: '∅ pas de solution',
    symmetricYes: 'symétrique oui',
    symmetricNo: 'pas symétrique',
    singularNoInv: 'A est singulière (det = 0), pas d’inverse',
    rank1Demo: 'approx. rang 1 (σ₂≈0)',
    rankFull: 'rang plein',
    encodeMsg: 'message m',
    codeword: 'mot de code c = mG',
    syndrome: 'syndrome s = Hcᵀ',
    validCodeword: 'mot valide (s=0)',
    invalidCodeword: 'erreur détectée (s≠0)',
    qrStep: 'Étape QR',
    svdUnit: 'cercle unité',
    makePerp: 'rendre ⊥',
  },
  it: {
    swap: 'Scambia',
    orderAb: 'Ordine a,b',
    groupLeft: 'Raggruppa a sinistra',
    groupRight: 'Raggruppa a destra',
    expandedForm: 'Forma sviluppata',
    reorderFactor: 'Riordina / fattorizza',
    closedEnds: 'Estremi chiusi',
    inputA: 'Ingresso A',
    inputB: 'Ingresso B',
    showTerms: 'Mostra termini',
    reflectH: 'Riflessione orizzontale',
    showBasis: 'Mostra base',
    dependent: 'dipendenti',
    independent: 'indipendenti',
    gramStep: 'Passo Gram-Schmidt',
    eigenvectors: 'Autovettori',
    applyInverse: 'Applica A⁻¹',
    svdStep: 'Passo SVD/QR',
    lowRank: 'Demo basso rango',
    luStep: 'Passo LU',
    roots2: '2 radici',
    root1: '1 radice',
    noRealRoot: 'nessuna radice reale',
    orientedArea: 'area orientata',
    noInverse: 'senza inverso',
    valid: 'valida',
    error: 'errore',
    dragVectors: 'Trascina le punte dei vettori.',
    tableAdd: 'Tabella +',
    tableMul: 'Tabella ·',
    subspaceNote: 'Somma c1+c2 = [1, 1, 0] (sottospazio chiuso)',
    homogeneousForm: 'forma omogenea grado',
    fallbackViz: 'Visualizzazione',
    time: 'Tempo',
    space: 'Spazio',
    algebraTiles: 'Tessere algebriche',
    termProduct: 'Prodotto termine × termine',
    augmented: 'b (aumentata)',
    result: 'risultato',
    clickBitError: 'clicca bit per errore',
    areaDet: 'area/det',
    fermatDemo: 'demo di Fermat',
    errorBit: 'errore',
    pascalRow: 'Riga di Pascal',
    addSquare: 'Aggiungi (b/2)²',
    subtractSquare: 'Sottrai (b/2)²',
    degreeLabel: 'Grado totale',
    degreeHint: 'Ogni asse contribuisce il suo esponente al grado',
    acute: 'acuto',
    rightAngle: 'retto',
    obtuse: 'ottuso',
    congruent: 'a ≡ b (mod m)',
    notCongruent: 'a ≢ b (mod m)',
    tableMatch: 'coincide con l’operazione',
    tableMismatch: 'non coincide — controlla la riga',
    equationOfRow: 'Equazione della riga',
    intersection: 'intersezione',
    solutionRegion: 'regione soluzione',
    noIntersection: 'nessuna intersezione (parallele)',
    svdRotate: 'Vᵀ: ruota',
    svdScale: 'Σ: scala',
    svdCompose: 'U: ricomponi',
    rankLabel: 'rango',
    cellProduct: 'prodotto riga×colonna',
    sameTotal: 'Stesso totale',
    compareBothSides: 'Confronta i due lati: muovendo a, b e c, le due aree cambiano allo stesso modo.',
    degreeUnits: 'unità di grado',
    powerMerge: 'Sotto i blocchi si uniscono: gli esponenti si sommano.',
    sameArea: 'stessa area',
    oneSolution: '1 soluzione',
    infSolutions: '∞ soluzioni',
    noSolution: '∅ nessuna soluzione',
    symmetricYes: 'simmetrica sì',
    symmetricNo: 'non simmetrica',
    singularNoInv: 'A è singolare (det = 0), nessuna inversa',
    rank1Demo: 'approx. rango 1 (σ₂≈0)',
    rankFull: 'rango pieno',
    encodeMsg: 'messaggio m',
    codeword: 'parola c = mG',
    syndrome: 'sindrome s = Hcᵀ',
    validCodeword: 'parola valida (s=0)',
    invalidCodeword: 'errore rilevato (s≠0)',
    qrStep: 'Passo QR',
    svdUnit: 'cerchio unitario',
    makePerp: 'rendi ⊥',
  },
  pt: {
    swap: 'Trocar',
    orderAb: 'Ordem a,b',
    groupLeft: 'Agrupar à esquerda',
    groupRight: 'Agrupar à direita',
    expandedForm: 'Forma expandida',
    reorderFactor: 'Reordenar / fatorar',
    closedEnds: 'Extremos fechados',
    inputA: 'Entrada A',
    inputB: 'Entrada B',
    showTerms: 'Mostrar termos',
    reflectH: 'Reflexão horizontal',
    showBasis: 'Mostrar base',
    dependent: 'dependentes',
    independent: 'independentes',
    gramStep: 'Passo Gram-Schmidt',
    eigenvectors: 'Autovetores',
    applyInverse: 'Aplicar A⁻¹',
    svdStep: 'Passo SVD/QR',
    lowRank: 'Demo baixo posto',
    luStep: 'Passo LU',
    roots2: '2 raízes',
    root1: '1 raiz',
    noRealRoot: 'sem raiz real',
    orientedArea: 'área orientada',
    noInverse: 'sem inverso',
    valid: 'válida',
    error: 'erro',
    dragVectors: 'Arraste as pontas dos vetores.',
    tableAdd: 'Tabela +',
    tableMul: 'Tabela ·',
    subspaceNote: 'Soma c1+c2 = [1, 1, 0] (subespaço fechado)',
    homogeneousForm: 'forma homogênea grau',
    fallbackViz: 'Visualização',
    time: 'Tempo',
    space: 'Espaço',
    algebraTiles: 'Peças algébricas',
    termProduct: 'Produto termo × termo',
    augmented: 'b (aumentada)',
    result: 'resultado',
    clickBitError: 'clique no bit para erro',
    areaDet: 'área/det',
    fermatDemo: 'demo de Fermat',
    errorBit: 'erro',
    pascalRow: 'Linha de Pascal',
    addSquare: 'Adicionar (b/2)²',
    subtractSquare: 'Subtrair (b/2)²',
    degreeLabel: 'Grau total',
    degreeHint: 'Cada eixo contribui com seu expoente para o grau',
    acute: 'agudo',
    rightAngle: 'reto',
    obtuse: 'obtuso',
    congruent: 'a ≡ b (mod m)',
    notCongruent: 'a ≢ b (mod m)',
    tableMatch: 'coincide com a operação',
    tableMismatch: 'não coincide — revise a linha',
    equationOfRow: 'Equação da linha',
    intersection: 'interseção',
    solutionRegion: 'região solução',
    noIntersection: 'sem interseção (paralelas)',
    svdRotate: 'Vᵀ: rotacionar',
    svdScale: 'Σ: escalar',
    svdCompose: 'U: recompor',
    rankLabel: 'posto',
    cellProduct: 'produto linha×coluna',
    sameTotal: 'Mesmo total',
    compareBothSides: 'Compara os dois lados: ao mover a, b e c, as duas áreas mudam igual.',
    degreeUnits: 'unidades de grau',
    powerMerge: 'Em baixo os blocos juntam-se: os expoentes somam-se.',
    sameArea: 'mesma área',
    oneSolution: '1 solução',
    infSolutions: '∞ soluções',
    noSolution: '∅ sem solução',
    symmetricYes: 'simétrica sim',
    symmetricNo: 'não simétrica',
    singularNoInv: 'A é singular (det = 0), sem inversa',
    rank1Demo: 'aprox. posto 1 (σ₂≈0)',
    rankFull: 'posto completo',
    encodeMsg: 'mensagem m',
    codeword: 'palavra c = mG',
    syndrome: 'síndrome s = Hcᵀ',
    validCodeword: 'palavra válida (s=0)',
    invalidCodeword: 'erro detectado (s≠0)',
    qrStep: 'Passo QR',
    svdUnit: 'círculo unitário',
    makePerp: 'fazer ⊥',
  },
};

export function useVizLabels(): VizLabels {
  const locale = useLocale() as AppLocale;
  return LABELS[locale] ?? LABELS.es;
}
