'use client';

import type { ReactNode } from 'react';
import { DET_EPS, Mat2Editor, cloneMat2, cols, matFromCols, rank2 } from './detHelpers';
import {
  applyMat,
  det2,
  inv2,
  linspace,
  matMul,
  type Mat2,
  type Vec2,
} from './math2d';
import { present } from './matrixGrid';

export { DET_EPS, Mat2Editor, cloneMat2, cols, matFromCols, rank2 };
export { applyMat, det2, inv2, matMul };

export const I2: Mat2 = [
  [1, 0],
  [0, 1],
];

export const PRESET_SHEAR: Mat2 = [
  [1, 0.8],
  [0, 1],
];

export const PRESET_SCALE: Mat2 = [
  [1.7, 0],
  [0, 0.6],
];

export const PRESET_SCALE_2: Mat2 = [
  [2, 0],
  [0, 0.5],
];

export const PRESET_ROT45: Mat2 = (() => {
  const c = Math.SQRT1_2;
  return [
    [c, -c],
    [c, c],
  ];
})();

export const PRESET_ROT90: Mat2 = [
  [0, -1],
  [1, 0],
];

export const PRESET_REFLECT_X: Mat2 = [
  [1, 0],
  [0, -1],
];

export const PRESET_PROJECT_X: Mat2 = [
  [1, 0],
  [0, 0],
];

export const PRESET_SINGULAR: Mat2 = [
  [1, 2],
  [2, 4],
];

export const PRESET_GENERAL: Mat2 = [
  [1.2, 0.4],
  [0.3, 0.9],
];

export const PRESET_ZERO: Mat2 = [
  [0, 0],
  [0, 0],
];

/** Asymmetric L-shape in the unit square (corner at origin). */
export const L_SHAPE: Vec2[] = [
  { x: 0, y: 0 },
  { x: 1.2, y: 0 },
  { x: 1.2, y: 0.4 },
  { x: 0.4, y: 0.4 },
  { x: 0.4, y: 1.2 },
  { x: 0, y: 1.2 },
];

export function formatPair(p: Vec2, digits = 2): string {
  const f = (n: number) => {
    if (Math.abs(n) < 1e-9) return '0';
    const r = Math.round(n);
    if (Math.abs(n - r) < 1e-8) return String(r);
    return present(Number(n.toFixed(digits)));
  };
  return `(${f(p.x)}, ${f(p.y)})`;
}

export function nearZero(v: Vec2, eps = DET_EPS): boolean {
  return Math.hypot(v.x, v.y) < eps;
}

export function vecEq(a: Vec2, b: Vec2, eps = 1e-6): boolean {
  return Math.hypot(a.x - b.x, a.y - b.y) < eps;
}

export function matEq(a: Mat2, b: Mat2, eps = 1e-6): boolean {
  return (
    Math.abs(a[0][0] - b[0][0]) < eps &&
    Math.abs(a[0][1] - b[0][1]) < eps &&
    Math.abs(a[1][0] - b[1][0]) < eps &&
    Math.abs(a[1][1] - b[1][1]) < eps
  );
}

export function matLerp(A: Mat2, t: number): Mat2 {
  const s = 1 - t;
  return [
    [s + t * A[0][0], t * A[0][1]],
    [t * A[1][0], s + t * A[1][1]],
  ];
}

export function transformPts(A: Mat2, pts: Vec2[]): Vec2[] {
  return pts.map((p) => applyMat(A, p));
}

/** Cartesian grid lines transformed by M (I = original). */
export function gridLines(
  M: Mat2,
  extent = 2.5,
  count = 11,
): Array<[Vec2, Vec2]> {
  const lines: Array<[Vec2, Vec2]> = [];
  for (const t of linspace(-extent, extent, count)) {
    lines.push([applyMat(M, { x: t, y: -extent }), applyMat(M, { x: t, y: extent })]);
    lines.push([applyMat(M, { x: -extent, y: t }), applyMat(M, { x: extent, y: t })]);
  }
  return lines;
}

/** Oblique lattice generated by integer combos of b1, b2. */
export function basisGridLines(
  b1: Vec2,
  b2: Vec2,
  kMax = 3,
): Array<[Vec2, Vec2]> {
  const lines: Array<[Vec2, Vec2]> = [];
  for (let k = -kMax; k <= kMax; k++) {
    const a = { x: k * b1.x - kMax * b2.x, y: k * b1.y - kMax * b2.y };
    const b = { x: k * b1.x + kMax * b2.x, y: k * b1.y + kMax * b2.y };
    lines.push([a, b]);
  }
  for (let l = -kMax; l <= kMax; l++) {
    const a = { x: -kMax * b1.x + l * b2.x, y: -kMax * b1.y + l * b2.y };
    const b = { x: kMax * b1.x + l * b2.x, y: kMax * b1.y + l * b2.y };
    lines.push([a, b]);
  }
  return lines;
}

export function polyPoints(
  pts: Vec2[],
  to: (p: Vec2) => { x: number; y: number },
): string {
  return pts.map((p) => {
    const q = to(p);
    return `${q.x},${q.y}`;
  }).join(' ');
}

export function ChipRow({ children }: { children: ReactNode }) {
  return (
    <div className="flex flex-wrap" style={{ display: 'flex', flexWrap: 'wrap', gap: 10 }}>
      {children}
    </div>
  );
}

export function BadgeRow({ children }: { children: ReactNode }) {
  return (
    <div style={{ display: 'flex', flexWrap: 'wrap', gap: 10, marginTop: 12, marginBottom: 12 }}>
      {children}
    </div>
  );
}

export function Chip({
  active,
  onClick,
  children,
  disabled,
}: {
  active?: boolean;
  onClick: () => void;
  children: ReactNode;
  disabled?: boolean;
}) {
  return (
    <button
      type="button"
      disabled={disabled}
      onClick={onClick}
      className={`rounded-md border px-2.5 py-1 text-xs font-medium transition-colors disabled:cursor-not-allowed disabled:opacity-40 ${
        active
          ? 'border-[var(--accent-strong)] bg-[var(--accent-soft)] text-[var(--fg)]'
          : 'border-[var(--border)] bg-[var(--bg)] text-[var(--fg-muted)] hover:border-[var(--accent-strong)]/50'
      }`}
    >
      {children}
    </button>
  );
}

export function Segmented({
  options,
  value,
  onChange,
}: {
  options: Array<{ id: string; label: string }>;
  value: string;
  onChange: (id: string) => void;
}) {
  return (
    <div
      className="inline-flex max-w-full flex-wrap rounded-lg border border-[var(--border)]"
      style={{ display: 'inline-flex', flexWrap: 'wrap', gap: 6, padding: 6 }}
    >
      {options.map((o) => (
        <button
          key={o.id}
          type="button"
          onClick={() => onChange(o.id)}
          className={`rounded-md px-3 py-2 text-xs font-medium transition-colors ${
            value === o.id
              ? 'bg-[var(--accent-soft)] text-[var(--fg)]'
              : 'text-[var(--fg-muted)] hover:text-[var(--fg)]'
          }`}
        >
          {o.label}
        </button>
      ))}
    </div>
  );
}

export function Badge({
  tone = 'neutral',
  children,
}: {
  tone?: 'ok' | 'bad' | 'warn' | 'neutral';
  children: ReactNode;
}) {
  const cls =
    tone === 'ok'
      ? 'border-emerald-600/40 bg-emerald-500/10 text-emerald-800 dark:text-emerald-300'
      : tone === 'bad'
        ? 'border-rose-600/40 bg-rose-500/10 text-rose-800 dark:text-rose-300'
        : tone === 'warn'
          ? 'border-amber-600/40 bg-amber-500/10 text-amber-900 dark:text-amber-200'
          : 'border-[var(--border)] bg-[var(--bg)] text-[var(--fg-muted)]';
  return (
    <span className={`inline-flex items-center rounded-md border px-2 py-0.5 text-xs font-medium ${cls}`}>
      {children}
    </span>
  );
}

export function CollapsibleEdit({
  label,
  open,
  onToggle,
  children,
}: {
  label: string;
  open: boolean;
  onToggle: () => void;
  children: ReactNode;
}) {
  return (
    <div className="viz-collapsible rounded-lg border border-[var(--border)]">
      <button
        type="button"
        onClick={onToggle}
        className="flex w-full items-center justify-between px-3 py-3 text-left text-sm font-medium text-[var(--fg)]"
      >
        {label}
        <span className="text-[var(--fg-muted)]">{open ? '▾' : '▸'}</span>
      </button>
      {open ? <div className="border-t border-[var(--border)] px-3 py-4">{children}</div> : null}
    </div>
  );
}

export function GuideBlock({
  idea,
  tryIt,
  concept,
}: {
  idea: string;
  tryIt: string;
  concept?: string;
}) {
  let tryBody = tryIt.trim();
  const prefix = /^(Pru[eé]balo)\s*[—–\-−:]\s*/i;
  while (prefix.test(tryBody)) {
    tryBody = tryBody.replace(prefix, '');
  }
  return (
    <div className="mb-5 space-y-2 text-sm leading-relaxed text-[var(--fg-muted)]">
      <p>{idea}</p>
      <p>
        <span className="font-medium text-[var(--fg)]">Pruébalo — </span>
        {tryBody}
      </p>
      {concept ? <p className="italic">{concept}</p> : null}
    </div>
  );
}
